---
- name: Templatize de-provision script
  template: src=deprovision_{{ provision_gce_ig_type }}.j2.sh dest=/tmp/deprovision.sh mode=u+rx

- name: De-provision GCE resources
  command: "/tmp/deprovision.sh"