---
- name: Generate htpasswd username and password
  shell: htpasswd -b {{ item[0].filename }} {{ item[1].user }} {{ item[1].passwd }}
  when: item[0].kind == 'HTPasswdPasswordIdentityProvider'
  with_nested:
  - "{{ openshift_master_identity_providers | default([]) }}"
  - "{{ provision_htpasswd_user_mappings | default([]) }}"
