---
- name: Copy content of extensions
  copy: src={{ item.name }}/ dest={{ item.sourceDirectory }}/
  with_items: "{{ openshift_master_extensions | default([]) }}"

- name: Login templates
  template: src={{ item }}.j2 dest={{ openshift_master_oauth_templates[item] }}
  with_items:
  - "{{ openshift_master_oauth_templates.keys() | default ([]) }}"
