# This playbook stops all instances when we're using unmanaged instance groups

- name: Stop all instances
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name:
    fail:
      msg: No unmanaged instance groups support this option
    when: provision_gce_ig_type != 'unmanaged'
  - name: Getting all instances
    shell: gcloud --project {{ gce_project_id }} compute instances list --filter='tags.items:{{ provision_prefix }} {{ change_status_tags | default('') }}' --format='value(name)'
    when: provision_gce_ig_type == 'unmanaged'
    register: instances
  - name: Stoping instances ...
    shell: gcloud compute instances stop {{ item }} --zone {{ gce_zone_name }}
    with_items: "{{ instances.stdout_lines | default([]) }}"
    async: 45
    poll: 0